// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CCC_Notes","status":true,"description":"Custom Quest Log for CCC Training Objectives (Auto-Wrap Version).","parameters":{}},
{"name":"CCC_QuizEngine","status":true,"description":"CCC Quiz Engine - Complete 50 MCQ Logic with Auto-Wrap.","parameters":{}},
{"name":"ForceDash","status":true,"description":"Forces dash to always be active.","parameters":{}}
];
